### ISSUE TITLE
Inconsitent sentence?

### ISSUE THREAD

**Issue by pojiro** [nerves-hub/documentation#5]
At first, thanks for your great works. I'm really interested in Nerves.

Now I'm confusing about terms of Nerves Key document.

My confusing part is below, quotes from https://github.com/nerves-hub/documentation/blob/5b1ed2dc48b5ffb75f7cd6bae17ab0018b580ebf/nerves-key/private-key-storage.md

> The NervesKey holds information for up to four certificates:
> 
> 1. A primary device certificate
> 2. The certificate that signed the primary device certificate
> 3. An auxiliary device certificate
> 4. The certificate that signed the auxiliary device certificate
>
> The provisioning procedure requires a signing certificate and creates the primary device certificate. Both certificates are recorded to the NervesKey. The auxiliary certificates are similar in function, but can be filled in later and rewritten.
> 
> The X.509 certificate that signs the device certificate is also called a Device Certificate Authority certificate \(Device CA certificate\) and must be uploaded to NervesHub for the device to be allowed to connect over TLS.

for simplicity, I just talk about 1 (a primary device certificate) and 2.

1 is signed by 2.
(So I think 1 is public key and 2 is private key, right?

2 is also called a signing certificate.
2 is also called a Device CA certificate in above sentence.

Next, confusing part is below, quotes from https://github.com/nerves-hub/documentation/blob/5b1ed2dc48b5ffb75f7cd6bae17ab0018b580ebf/nerves-key/provisioning-in-elixir.md

> To provision a NervesKey, make sure that you have the following:
> 
> 1. A Device CA certificate and its private certificate \(this is also referred to as a signing certificate\)
> 
> 2. A serial number for your device
> 3. A name for the device

In this sentence "A Device CA certificate" seems public key.

I feel there is inconsistency.

**Comment by fhunleth** [comment]
There's a difference between certificate and public key: a public key is included in a certificate. Certificates also contain other metadata.

There's no difference between device CA certificate and signer certificate. 

I prefer "signer certificate" since I like how accurately it describes the use of the certificate. However, I've found that pretty much every one else coming from web and backend dev feels more comfortable calling it a CA certificate (as in a CA certificate for devices. as in a device CA certificate). Having said that, we had a recent discussion on this and started leaning towards calling this a signing certificate and changing every CA certificate reference to signing certificate to avoid confusion. No changes have been made, though.

Does this help?

**Comment by pojiro** [comment]
Thanks for your reply.

Could you check my recognition of these terms ?

- "Device CA certificate" is also called "signer certificate" or "primary device certificate" and  it includes public key
- "Device CA's private key" is also called  "private certificate" or "signing certificate"


If above is true, I wonder the below sentence.

> The X.509 certificate that signs the device certificate is also called a Device Certificate Authority certificate (Device CA certificate) and must be uploaded to NervesHub for the device to be allowed to connect over TLS.

"The X.509 certificate" is private key, isn't it? If so, I think the private key is not a Device CA certificate and must not be uploaded to NervesHub.

**Comment by fhunleth** [comment]
No. The "primary device certificate" is not the "signer certificate". There are only two kinds of certificates in this system: a device has a device certificate and the factory has a signing certificate. Each device certificate is different and uniquely identifies the device to cloud servers. The cloud server can check that the device certificate is valid by verifying that it is signed by the factory's signing certificate.

To support development and a few other scenarios, devices can possess multiple certificates. With the NervesKey, there's support for two: a primary one and an auxiliary one. 

X.509 is a standard that says how to encode the bytes in the certificate. Both certificates and private keys are stored according to the X.509 specification.

**Comment by pojiro** [comment]
Thank you Frank! I finally understand what I misunderstood. I did not understand who creates a device cert.
Thank you for your patience. And excuse me, I'm sorry.

`mix nerves_key.signer create` command create a signer cert and its key.
This signer cert is stored by factory.
And this signer cert is self signed cert like root CA. So it is also called Device CA cert.

`NervesKey.provision` function create device cert and which is signed by signer key.
The device cert and signer cert is stored in NervesKey by the function.

I prefer to call a Device CA's private key a signer key rather than calling signing certification because I think key is just key not cert. But I'm non-native English speaker, so I don't know the nuance native has.

Thanks a lot and I'm sorry for spending your time.

**Comment by fhunleth** [comment]
I agree. I find the term "signer key" more precise and prefer it as well. 

While I don't always respond promptly, I appreciate it when people ask questions when something is not clear. It helps us improve the documentation when we work on it.
